routes/web.php
Route::get('/order-gift/{id}', 'UserOrderController@getGiftCardDetail');
Route::get('/order-gift-archive', 'UserOrderController@giftCardArchiveOrder');
Route::get('/order-gift-archive/{id}', 'UserOrderController@getGiftCardArchiveDetail');
Route::get('/order-gift-export', 'UserOrderController@giftExport');
Route::resource('manage_orders', 'ManageOrderController');
$router->get('manage_orders/{id}/details', ['uses' => 'ManageOrderController@orderDetail']);
$router->get('manage_archive_order', ['uses' => 'ManageOrderController@archiveOrder']);
Route::put('/morders/{id}/{action}', 'ManageOrderController@updateOrderStatus');
Route::post('/morders/cancel', 'ManageOrderController@cancelOrder');
Route::get('/dashboard/movetoarchive', 'MoveOrderToArchiveController@index');
Route::get('/dashboard/movetoactive', 'MoveOrderToActiveController@index');
Route::resource('static', 'StaticController');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/dashboard/call', 'CallSentController@sentCall');
Route::resource('users', 'UserController');
Route::get('/restaurant/{restaurant_id}/import', 'ImportController@index');
Route::post('/restaurant/{restaurant_id}/import', 'ImportController@save');
Route::resource('restaurant-old', 'RestaurantController');
Route::resource('pizzaexp', 'PizzaExpController');
Route::resource('pizzaexpitem', 'PizzaExpItemController');
Route::get('/pizzaexpitem/{id}/delete/{item}', 'PizzaExpItemController@delete');
Route::resource('static', 'StaticController');
Route::resource('block', 'BlockController');
Route::get('enquiry/{type}/{enctype?}', ['uses' => 'BlockController@getRequestList'])->name('enquiry');
Route::get('enquirydetail/{id}', 'BlockController@requestDetails');
Route::get('contactenquirydetail/{id}', 'BlockController@contactDetails')->name('contactDetails');
Route::get('careerdetails/{id}', 'BlockController@careerDetails');
Route::get('eventdetail/{id}', 'BlockController@eventDetails');
Route::post('enquiryreplymail', 'BlockController@enquirySendMail');
$router->get('block/{id}/info', ['uses' => 'BlockController@requestDetails']);
Route::get('staticblock', ['uses' => 'StaticController@createBlock']);
Route::post('static/create', 'StaticController@saveBlock');
Route::get('block_list', ['uses' => 'StaticController@getblock']);
Route::get('static_editblock/{id}', ['uses' => 'StaticController@edit_block']);
Route::post('static_editblock', 'StaticController@saveEditBlock');
Route::get('static_deleteblock/{id}', ['uses' => 'StaticController@deleteBlock']);
Route::resource('menu', 'MenuController');
Route::resource('menu_category', 'MenuCategoryController');
Route::get('/get_sub_cats_group', 'MenuSubcategoryController@getSubcatsGroup');
Route::resource('menu_subcategory', 'MenuSubcategoryController');
Route::resource('menu_meal_type', 'MenuMealTypeController');
Route::get('menu_products', 'MenuItemController@product');
Route::get('menu_giftcards', 'MenuItemController@giftcard');
Route::get('menu_giftcards/{id}', 'MenuItemController@giftCardDetail');
Route::resource('menu_item', 'MenuItemController');
Route::resource('menu_setting_category', 'MenuSettingCategoryController');
Route::resource('menu_setting_item', 'MenuSettingItemController');
Route::resource('languages', 'LanguagesController');
Route::resource('localization', 'LocalizationController');
Route::post('/get_category_and_type', 'MenuItemController@getCategoryAndType');
Route::post('/get_availibility', 'MenuItemController@getAvailibility');
Route::post('/get_customization_options', 'MenuItemController@getCustomizationOptions');
Route::post('/get_category', 'MenuCategoryController@getCategory');
Route::post('/get_menu_setting_category', 'MenuSettingCategoryController@getSettingCategory');
Route::post('/set_language', 'HomeController@setLanguage');
Route::resource('sms', 'SmsContentController'); //https://laravel.com/docs/5.6/controllers
Route::POST('sms/create', 'SmsContentController@addSmsContent');
Route::get('sms/{id}/update', 'SmsContentController@editSms');
Route::resource('mailtemplate', 'MailTemplateController');
Route::POST('mailtemplate/create', 'MailTemplateController@addTemplate');
Route::get('mailtemplate/{id}/update', 'MailTemplateController@editTemplate');
// AJAX calls
Route::post('/get_restaurant_settings', 'PizzaExpController@getRestaurantSettings');
Route::post('/get_restaurant_locations', 'MenuCategoryController@get_restaurant_locations');
Route::post('/get_cities_by_state', 'CmsUserController@get_cities_by_state');
Route::post('/get_restaurant_by_city', 'CmsUserController@get_restaurant_by_city');
Route::post('/get_static_blocks', 'BlockController@getStaticBlocks');
//reports
Route::get('report/download', 'ReportsController@download');
Route::get('report/locations',      'ReportsController@locations');
Route::get('report/orders',         'ReportsController@orders');
Route::get('report/reservations',   'ReportsController@reservations');
Route::get('report/visitors',       'ReportsController@visitors')->name('visitorsreport');
Route::get('report/marketing',      'ReportsController@marketing')->name('marketingreport');
Route::get('report/social',         'ReportsController@social')->name('socialreport');
Route::get('reports', 'ReportsController@index')->name('reports');
Route::post('/get_states', 'RestaurantController@getStates')->name('getstate');
$router->get('update/sides/quantity', function() {
    exec('php c:\wamp\apache2\htdocs\multipage_cms\artisan cache:clear');
    $menuItemObj = \App\Models\MenuItem::orderBy('id', 'DESC')->get();
    $menuItems = $menuItemObj->toArray();
    foreach ($menuItems as $menuItem) {
        if (!empty($menuItem['customizable_data'])) {
            $custData = json_decode($menuItem['customizable_data'], true);
            $tmpCustData = $custData;
            foreach ($custData as $k => $v) {
                if (!empty($v) && is_array($v)) {
                    foreach ($v['items'] as $k1 => $v1) {
                        if (!empty($v1) && is_array($v1) && isset($v1['sides'])) {
                            $tmpSidesArr = array();
                            foreach ($v1['sides'] as $k2 => $v2) {
                                if (!empty($v2['is_selected'])) {
                                    $tmpSidesArr[] = $v2;
                                }
                            }
                            if (count($tmpSidesArr) > 0)
                                $custData[$k]['items'][$k1]['sides'] = $tmpSidesArr;
                            else
                                $custData[$k]['items'][$k1]['sides'] = NULL;
                            $tmpQuanArr = array();
                            foreach ($v1['quantity'] as $k2 => $v2) {
                                if (!empty($v2['is_selected'])) {
                                    $tmpQuanArr[] = $v2;
                                }
                            }
                            if (count($tmpQuanArr) > 0)
                                $custData[$k]['items'][$k1]['quantity'] = $tmpQuanArr;
                            else
                                $custData[$k]['items'][$k1]['quantity'] = NULL;
                            //echo "mmmm".$custData[$k]['items'][$k1]['sides'][0]['is_selected'];
                        }
                    }
                }
            }
            \App\Models\MenuItem::where('id', $menuItem['id'])
                ->update(['customizable_data' => json_encode($custData)]);
            
        }
    }
    echo "Data updated";
    exit;
});
// Route for Clickatell customer response
Route::get('online-waitlist-status', '\Modules\Reservation\Http\Controllers\ReservationController@onlineWaitlistStatus');
 
# Route By Rahul Gupta 10-07-2018
Route::resource('countries', 'CountryController');
Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'configure'], function() {
    Route::resource('carryout-hours', 'CarryoutHoursController');
    Route::get('carryout-hours-schedule', 'CarryoutHoursController@getWorkingHoursSchedule');
    Route::get('custom-carryout-hours-schedule', 'CarryoutHoursController@getCustomWorkingHoursSchedule');
    Route::post('carryout-hours-dayoff', 'CarryoutHoursController@dayOffToggle');
    Route::get('carryout-slot-detail/{id}', 'CarryoutHoursController@getSlotDetail');
    Route::resource('delivery-hours', 'DeliveryHoursController');
    Route::get('delivery-hours-schedule', 'DeliveryHoursController@getWorkingHoursSchedule');
    Route::get('custom-delivery-hours-schedule', 'DeliveryHoursController@getCustomWorkingHoursSchedule');
    Route::post('delivery-hours-dayoff', 'DeliveryHoursController@dayOffToggle');
    Route::get('delivery-slot-detail/{id}', 'DeliveryHoursController@getSlotDetail');
    Route::resource('operation-hours', 'OperationHoursController');
    Route::get('operation-hours-schedule', 'OperationHoursController@getOperationHoursSchedule');
    Route::get('custom-operation-hours-schedule', 'OperationHoursController@getCustomOperationHoursSchedule');
    Route::post('operation-hours-dayoff', 'OperationHoursController@dayOffToggle');
    Route::get('operation-slot-detail/{id}', 'OperationHoursController@getSlotDetail');
    #RG 29-01-2019 Manage Services
    Route::get('/manage_services', 'RestaurantController@manageServices');
    Route::post('/restaurantsettings', 'RestaurantController@restaurantsettings');
});
// Code changes done by Jawed for menu visibility hours.
Route::group(['middleware' => ['web', 'auth'], 'prefix' => 'configure'], function()
{
    Route::resource('visibility-duration', 'VisibilityDurationController');
    Route::post('visibility-duration-schedule', 'VisibilityDurationController@getVisibilityHoursSchedule');
    Route::get('custom-visibility-duration-schedule', 'VisibilityDurationController@getCustomVisibilityHoursSchedule');

app/Models/Language.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;


class Language extends Authenticatable
{
    use Notifiable;

    protected $table = 'languages';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'language_name', 'code', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at', 'updated_at'
    ];

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }
  /*  public function restaurant()
    {
        return $this->belongsTo('App\Models\Restaurant');
    }
    public function order()
    {
        return $this->hasMany('App\Models\UserOrder');
    }

    public function address()
    {
        return $this->hasMany('App\Models\UserAddresses');
    }

    public function card()
    {
        return $this->hasMany('App\Models\UserCards');
    }*/
}

app/Http/Controllers/LanguagesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;

class LanguagesController extends Controller
{
    /**
     * User listing
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $languages = Language::orderBy('id', 'DESC')->paginate(6);

        return view('languages.index', compact('languages'));
    }

    /**
     * Create Languages
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {

        return view('languages.create');
    }

    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'language_name' => 'required|max:255',
            'code'         => 'required|max:255'
        ]);
        if (!$validator->fails()) {
            $data = [
                'language_name' => strtolower($request->input('language_name')),
                'code'         => strtolower($request->input('code')),
                'status'        => $request->input('status'),
                'updated_at'        => now()
            ];
            //dd([$request->all(),2]);
            Language::create($data);
            return redirect('/languages')->with('message', 'Language added successfully');

        } else {
            //dd([$request->all(), '1', $validator->errors()]);

            return Redirect::back()->withErrors($validator->errors())->withInput();
        }

    }
    
    /**
     * User edit
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)

    {
        $languages = Language::find($id);
        return view('languages.edit', compact('languages'));
    }

    /**
     * User edit update
     * @param Request $request
     * @param         $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        if(isset($id) && is_numeric($id)) {
            $languages = Language::find($id);
            $validator = Validator::make($request->all(), [
                'language_name'         => 'required|max:255',
                'code'           => 'required|max:255',
            ]);

            if(!$validator->fails()) {

                $languages->language_name = $request->input('language_name');
                $languages->code = $request->input('code');
                $languages->updated_at = now();
                $languages->status = $request->input('status');
                $languages->save();

                return redirect('/languages')->with('message', 'Language updated successfully');

            } else {

                return Redirect::back()->withErrors($validator->errors())->withInput();
            }
        }

        return Redirect::back()->with('message', 'Invalid Id');
    }
}

resources/views/languages/create.blade.php
@extends('layouts.app')
@section('content')
<div class="main__container container__custom">
  <div class="reservation__atto">
    <div class="reservation__title">
      <h1>{{ __('Language - Create') }}</h1>

    </div>

  </div>
  <div class="justify-content-center" style="width:80%;float:left;margin-left:10px;">

    <div class="card form__container">
      @if(session()->has('message'))
      <div class="alert alert-success">
        {{ session()->get('message') }}
      </div>
      @endif
      <div class="card-body">
        <div class="form__user__edit">
          <form method="POST" action="{{ route('languages.store') }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group row form_field__container">
              <label for="fname" class="col-md-4 col-form-label text-md-right">{{ __('Language Name') }}</label>
              <div class="col-md-4">
                <div class="input__field">

                  <input id="language_name" type="text" class="{{ $errors->has('language_name') ? ' is-invalid' : '' }}"
                  name="language_name" value="{{ old('language_name') }}" required autocomplete="off">
                </div>
                @if ($errors->has('language_name'))
                <span class="invalid-feedback">
                  <strong>{{ $errors->first('language_name') }}</strong>
                </span>
                @endif
              </div>
            </div>
            <div class="form-group row form_field__container">
              <label for="lname" class="col-md-4 col-form-label text-md-right">{{ __('Language Code') }}</label>
              <div class="col-md-4">
                <div class="input__field">
                  <input id="code" type="text" class="{{ $errors->has('code') ? ' is-invalid' : '' }}"
                  name="code" value="{{ old('code') }}" required autocomplete="off">
                </div>
                @if ($errors->has('code'))
                <span class="invalid-feedback">
                  <strong>{{ $errors->first('code') }}</strong>
                </span>
                @endif
              </div>
            </div>

            <div class="form-group row form_field__container">
              <label for="priority" class="col-md-4 col-form-label text-md-right">{{ __('Status') }}</label>
              <div class="col-md-4" style="padding-top: 10px;">
                <input type="radio" id="status1" name="status" value="1" checked> Active
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" id="status0" name="status" value="0" > Inactive
                @if ($errors->has('status'))
                <span class="invalid-feedback" style="display:block;">
                  <strong>{{ $errors->first('status') }}</strong>
                </span>
                @endif
              </div>
            </div>
            <br /><br />
            <div class="row mb-0">
              <div class="col-md-12 text-center">
                <button type="submit" class="btn btn__primary">{{ __('Save Language') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>
</div>
@endsection

resources/views/languages/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="main__container container__custom">
  <div class="reservation__atto">
    <div class="reservation__title">
      <h1>{{ __('Language - Edit') }}</h1>

    </div>

  </div>
  <div>

    <div class="card form__container">
      <div class="card-header"></div>
      @if(session()->has('message'))
      <div class="alert alert-success">
        {{ session()->get('message') }}
      </div>
      @endif
      <div class="card-body">
        <div class="form__user__edit">
          {{ Form::model($languages, array('route' => array('languages.update', $languages->id), 'method' => 'PUT', 'files' => true)) }}
          @csrf
          <div class="form-group row form_field__container">
            <label for="fname" class="col-md-4 col-form-label text-md-right">{{ __('Language Name') }}</label>
            <div class="col-md-4">
              <div class="input__field">
                <input id="language_name" type="text" class="{{ $errors->has('language_name') ? ' is-invalid' : '' }}"
                name="language_name" value="{{ count(old())==0 ? $languages->language_name : old('language_name')}}" required autocomplete="off">
              </div>
              @if ($errors->has('language_name'))
              <span class="invalid-feedback">
                <strong>{{ $errors->first('language_name') }}</strong>
              </span>
              @endif
            </div>
          </div>
          <div class="form-group row form_field__container">
            <label for="lname" class="col-md-4 col-form-label text-md-right">{{ __('Language Code') }}</label>
            <div class="col-md-4">
              <div class="input__field">
                <input id="code" type="text" class="{{ $errors->has('code') ? ' is-invalid' : '' }}"
                name="code" value="{{ count(old())==0 ? $languages->code : old('code') }}" required autocomplete="off">
              </div>
              @if ($errors->has('code'))
              <span class="invalid-feedback">
                <strong>{{ $errors->first('code') }}</strong>
              </span>
              @endif
            </div>
          </div>

          <div class="form-group row form_field__container">
            <label for="priority" class="col-md-4 col-form-label text-md-right">{{ __('Status') }}</label>
            <div class="col-md-4" style="padding-top: 10px;">
              <input type="radio" id="status1" name="status" value="1" {{ (old('status')=='1' || (count(old())==0 && $languages->status=='1')) ? 'checked' :'' }}> Active
              &nbsp;&nbsp;&nbsp;&nbsp;
              <input type="radio" id="status0" name="status" value="0" {{ (old('status')=='0' || (count(old())==0 && $languages->status=='0')) ? 'checked' :'' }}> Inactive
              @if ($errors->has('status'))
              <span class="invalid-feedback" style="display:block;">
                <strong>{{ $errors->first('status') }}</strong>
              </span>
              @endif
            </div>
          </div>


          <br /><br />
          <div class="row mb-0">
            <div class="col-md-12 text-center">
              <button type="submit" class="btn btn__primary">{{ __('Save Language') }}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

</div>
</div>
@endsection

resources/views/languages/index.blade.php
@extends('layouts.app')

@section('content')
<div class="main__container container__custom">
  <div class="reservation__atto">
    <div class="reservation__title">
      <h1>Users<span style="margin:0px 5px;">({{ $languages->currentPage() .'/' . $languages->lastPage() }})</span>&emsp;</h1>
    </div>
    <span style="float: right;margin:0px 5px;"><a href="{{ URL::to('languages/create') }}" class="btn btn__primary">Add</a></span>
  </div>
  <div class="addition__functionality">
    {!! Form::open(['method'=>'get']) !!}
    <div class="row functionality__wrapper">
      <div class="row form-group col-md-2">
        <div class="input__field">
          <input id="sName" class=""  type="text" name="name" value="{{isset($searchArr['name']) ? $searchArr['name'] : ''}}">
          <label for="sName">Name</label>
        </div>
      </div>
      <div class="row form-group col-md-3">
        <button class="btn btn__primary" style="margin-left: 5px;" type="submit" >Search</button>
      </div>
    </div>
    {!! Form::close() !!}
  </div>




  <div>

    <div class="active__order__container">

      @if(session()->has('message'))
      <div class="alert alert-success">
        {{ session()->get('message') }}
      </div>
      @elseif (session()->has('err_msg'))
      <div class="alert alert-danger">
        {{ session()->get('err_msg') }}
      </div>
      @endif

      <div class="guestbook__container box-shadow">
        <div class="guestbook__table-header hidden-xs hidden-sm hidden-tablet row plr0">
          <div class="col-md-10">
            <div class="col-md-2" style="font-weight: bold;">Language</div>
            <div class="col-md-1" style="font-weight: bold;">Code</div>
            <div class="col-md-3" style="font-weight: bold;">Created On</div>
            <div class="col-md-3" style="font-weight: bold;">Updated On</div>
            <div class="col-md-1" style="font-weight: bold;">Status</div>
          </div>
          <div class="col-md-2">
            <div class="col-md-12" style="font-weight: bold;">Action</div>
          </div>
        </div>
        @if(isset($languages) && count($languages)>0)
        @foreach($languages as $lang)
        <div class="guestbook__customer-details-content rest__row">
          <div class="col-md-10">

            <div class="col-md-2 text-capitalize" style="margin: auto 0px;">{{ $lang->language_name }}</div>
            <div class="col-md-1 text-capitalize" style="margin: auto 0px;">{{ $lang->code }}</div>
            <div class="col-md-3 text-capitalize" style="margin: auto 0px;">{{ $lang->created_at }}</div>
            <div class="col-md-3 text-capitalize" style="margin: auto 0px;">{{ $lang->updated_at }}</div>
            <div class="col-md-1 text-capitalize" style="margin: auto 0px;">{{ ($lang->status==1)?'Active':($lang->status==0?'Inactive':'') }}</div>

          </div>
          <div class="row col-md-2" style="margin: auto 0px;">
            <div class="col-md-12">
              <a style="width:100%;margin:10px 0;" href="{{ URL::to('languages/' . $lang->id . '/edit') }}" class="btn btn__primary"><span class="fa fa-pencil"></span> Edit</a>
            </div>
            {{--<div class="col-md-7">--}}
              {{--{!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $lang->id]]) !!}--}}
              {{--@csrf--}}
              {{--<button class="btn btn-default" type="submit">Delete</button>--}}
              {{--{!! Form::close() !!}--}}
              {{--</div>--}}
            </div>
          </div>
          @endforeach
          @else
          <div class="row" style="text-align: center;justify-content: center;border:1px solid rgba(0, 0, 0, 0.03);">
            No Record Found
          </div>
          @endif
        </div>

        @if(isset($languages) && count($languages)>0)
        <div style="margin: 0px auto;">
          {{ $languages->appends($_GET)->links()}}
        </div>
        @endif
      </div>

    </div>
  </div>
  @endsection