Modules/MenuManagement/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'prefix' => '/menu/', 'namespace' => 'Modules\MenuManagement\Http\Controllers'], function() {
    // Route::get('/label/list', 'ItemLabelsController@index');
    Route::get('merchandise', 'MenuItemController@product');
	
    Route::resource('label', 'ItemLabelsController');
    Route::resource('modifier-group', 'ItemModifierGroupController');
    Route::post('item/images/{id}', 'MenuItemController@imagesupdate');
    Route::post('item/modifiergroup/{id}/{languageId}', 'MenuItemController@modifiergroup');
    Route::post('item/modifiergroup/{id}', 'MenuItemController@modifiergroup');
    Route::delete('modifieritem/{id}', 'MenuItemController@deleteModifierItem');
    Route::get('modifieritem/{id}/{languageId}', 'ItemModifierController@getModifierItemInfo');
    Route::get('modifieritem/{id}', 'ItemModifierController@getModifierItemInfo');
    Route::post('item/modifieroptiongroup', 'ItemModifierController@saveItemModifierOptionGroup');
    Route::delete('item/modifieroptiongroup/{id}', 'ItemModifierController@deleteModifierItemOptionGroup');
    Route::post('item/modifieroption/{id}', 'ItemModifierController@saveModifierOption');
    Route::delete('modifieroption/{id}', 'ItemModifierController@deleteModifierOption');

    Route::get('item/{id}/edit/{language_id}', 'MenuItemController@edit');
    Route::get('item/{id}/destroy/', 'MenuItemController@destroy');	
    Route::resource('item', 'MenuItemController');
    
    Route::resource('item-addon-groups', 'ItemAddonGroupsController');
    Route::get('item-addon-groups/list/{restaurantId}/{menuItemId}/{languageId}', 'ItemAddonGroupsController@index');
    Route::post('item-addon-groups/add', 'ItemAddonGroupsController@store');
    Route::put('item-addon-groups/update/{addonGroupId}', 'ItemAddonGroupsController@update');
    Route::delete('item-addon-groups/destroy/{id}', 'ItemAddonGroupsController@destroy');
    Route::resource('item-addons', 'ItemAddonsController');
    Route::get('item-addons/list/{restaurantId}/{addonGroupId}', 'ItemAddonsController@menuitems');
    Route::post('item-addons/add', 'ItemAddonsController@store');
    Route::delete('item-addons/destroy/{id}', 'ItemAddonsController@destroy');

    Route::get('modifier_categories', 'ModifierCategoriesController@index');
    Route::get('modifier_categories/create', 'ModifierCategoriesController@create');
    Route::post('modifier_categories/store', 'ModifierCategoriesController@store');
    Route::get('modifier_categories/{id}/edit', 'ModifierCategoriesController@edit');
    Route::put('modifier_categories/update/{id}', 'ModifierCategoriesController@update');
    Route::delete('modifier_categories', 'ModifierCategoriesController@destroy');

    Route::get('menu-item-visibility/list/{restaurantId}/{menuItemId}', 'MenuItemsVisibilityController@index');
    Route::get('menu-item-visibility/add/{visibilityScheduleId}/{menuItemId}', 'MenuItemsVisibilityController@store');
    Route::get('merchandise', 'MenuItemController@product');
    Route::get('localization', 'LocalizationController@index');
    Route::get('localization/create', 'LocalizationController@create');
    Route::post('localization/store', 'LocalizationController@store');
    Route::get('localization/{id}/edit', 'LocalizationController@edit');
    Route::put('localization/update/{id}', 'LocalizationController@update');
    Route::delete('localization/{id}', 'LocalizationController@destroy');

    Route::get('all_items', 'MenuItemController@all_items');
    Route::get('schedules', 'MenuItemController@schedules');
    Route::get('modifiers', 'MenuItemController@modifiers');
    Route::get('labels', 'MenuItemController@labels');

    // MENU MANAGEMENT - AJAX Calls
    Route::post('get_data',                 'MenuItemController@getData');              // Temp route to test

    Route::get('all_cat_sub_cat',           'MenuItemController@allCatSubCatList');     // All Categories and Sub-Categories
    Route::post('get_cat_sub_cat',          'MenuItemController@getCatSubCat');         // Get a Category and its Sub-Categories
    Route::post('save_cat_sub_cat',         'MenuItemController@storeCatSubCat');       // Store Categories and Sub-Categories - NOT IN USE
    Route::post('menu_items',               'MenuItemController@getMenuItems');         // Menu items for a category or subcategory
    Route::get('menu_item/{id}',            'MenuItemController@getMenuItem');          // Get single menu item details
    Route::post('add_category',             'MenuItemController@addCategory');          // Add new Category
    Route::post('delete_category_file',     'MenuItemController@deleteCategoryFile');   // Delete Category file
    Route::post('add_menu_item',            'MenuItemController@addMenuItem');          // Add/Update new menu item
    Route::get('get_modifier_groups',       'MenuItemController@getModifierGroups');    // Get Modifier Groups
    Route::get('get_modifier_categories',   'MenuItemController@getModifierCategories');// Get Modifier Categories
    Route::post('save_modifier_group',      'MenuItemController@saveModifierGroups');   // Save Modifier Groups
    Route::post('save_addon_group',         'MenuItemController@saveAddonGroups');      // Save Addon Groups
    Route::post('save_label_data',          'MenuItemController@saveLabelData');        // Save Label data
    Route::post('save_menu_image',          'MenuItemController@saveMenuImage');        // Save Modifier Groups
    Route::post('validate_cat_slug',        'MenuItemController@validateCatSlug');      // Save Modifier Groups

    Route::post('toggleactive',             'MenuItemController@toggleMenuActive');     // Toggle menu active status
    Route::post('/item/modifieritem/options/add', 'MenuItemController@addModiferOptions');
    Route::get('/item/modifieritem/options/list/{id}', 'MenuItemController@listModiferOptions');
});

/*
Route::group(['middleware' => 'web', 'prefix' => '/v2/menu', 'namespace' => 'Modules\MenuManagement\Http\Controllers\v2'], function() {
    
    //Route::resource('modifier-group', 'ItemModifierGroupController');
    Route::get('item/{menu_id}/edit-item', 'MenuItemController@editItem');
    Route::get('item/{cat_id}/{rest_id}/{sort_type_id}/list', 'MenuItemController@index');
    Route::get('item/{cat_id}/{rest_id}/{sort_type_id}/{category_filter_by}/{product_type_filter_by}/{status_filter_by}/{type_filter_by}/list', 'MenuItemController@index');			
    Route::post('item/{menu_id}/update-type', 'MenuItemController@updateItemType');	
    Route::post('item/images/{id}', 'MenuItemController@imagesupdate');
    
    //Route::post('item/modifiergroup/{id}', 'MenuItemController@modifiergroup');
    Route::delete('modifieritem/{id}', 'MenuItemController@deleteModifierItem');
    Route::get('modifieritem/{id}/{languageId}', 'ItemModifierController@getModifierItemInfo');
    Route::get('modifieritem/{id}', 'ItemModifierController@getModifierItemInfo');
    Route::post('item/modifieroptiongroup', 'ItemModifierController@saveItemModifierOptionGroup');
    Route::delete('item/modifieroptiongroup/{id}', 'ItemModifierController@deleteModifierItemOptionGroup');
    Route::post('item/modifieroption/{id}', 'ItemModifierController@saveModifierOption');
    Route::delete('modifieroption/{id}', 'ItemModifierController@deleteModifierOption');

    Route::get('item/{id}/edit/{language_id}', 'MenuItemController@edit');
    Route::get('item/{id}/destroy/', 'MenuItemController@destroy');	
    Route::resource('item', 'MenuItemController');
    //////////////////////Route::get('/item/generalinfo', 'MenuItemController@index');	
     
    Route::post('item/generalinfo', 'MenuItemController@generalInfo')->name('menu-item-add');
    //Route::get('item/generalinfo', 'MenuItemController@generalInfo')->name('menu-item-add-redirect');	
    Route::post('item/attributeinfo', 'MenuItemController@attributeInfo');
    Route::post('/get_category', 'MenuItemController@getCategory')->name('category-data');	
    Route::post('/get_sub_category', 'MenuItemController@getSubCategory')->name('category-data');
    Route::get('item/{menu_id}/addprice', 'MenuItemController@addPrice')->name('menu-item-price-add');
    Route::get('item/{menu_id}/addinventory', 'MenuItemController@addInventoryInfo')->name('menu-item-inventory-add');
    Route::post('/item/{menu_id}/updateinventory', 'MenuItemController@addUpdateInventory')->name('menu-item-inventory-update');

    Route::post('/item/{menu_id}/updateprice', 'MenuItemController@addUpdatePrice')->name('menu-item-price-update');
    Route::get('/item/associatedproduct/{menu_id}/list', 'MenuItemController@listAssociatedProduct')->name('menu-item-list-associated');
    Route::post('/item/associatedproduct/{menu_id}/add', 'MenuItemController@addAssociatedProduct')->name('menu-item-add-associated');
    Route::post('item/modifiergroup/{menu_id}', 'MenuItemController@modifiergroup');
    Route::get('item/modifiergroup/{menu_id}/list', 'MenuItemController@listModifiers')->name('menu-modifier-group-list');
    Route::get('item/modifiergroup/item/{modifier_id}', 'MenuItemController@listModifierItem')->name('menu-modifier-item-list');
    Route::get('item/modifiergroup/iteminfo/{id}', 'MenuItemController@getModifierItemInfo')->name('menu-modifier-item-info');		
    Route::post('item/{menu_id}/addmodifiergroup', 'MenuItemController@createModfierGroup')->name('menu-modifier-group-add');
    Route::post('item/{menu_id}/addmodifiergroupitem', 'MenuItemController@createModfierGroupItem')->name('menu-modifier-group-item-add');
    Route::delete('item/modifiergroup/itemdelete/{id}/', 'MenuItemController@destroyModifierItem')->name('menu-addon-item-delete');
    Route::post('item/{menu_id}/updatemodifiergroup', 'MenuItemController@updatemodifiergroup')->name('menu-modifier-group-item-add');

	
    Route::get('/item/{menu_id}/editgeneralinfo', 'MenuItemController@editGeneralInfo')->name('menu-item-edit');

Modules/MenuManagement/Entities/ItemModifierGroup.php
<?php

namespace Modules\MenuManagement\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ItemModifierGroup extends Model
{
	use SoftDeletes;

    protected $fillable = ['restaurant_id','group_name','prompt','language_id','is_required','quantity_type','quantity','menu_item_id','pos_id', 'calorie','sort_order','status','show_as_dropdown','description'];
    protected $table='modifier_groups';

    protected $dates = ['deleted_at'];

    
    public function restaurant()
    {
        return $this->belongsTo('App\Models\Restaurant');
    }

    public function itemmodifiers()
    {
        return $this->hasMany('Modules\MenuManagement\Entities\ItemModifier','modifier_group_id');
    }

     public function modifierGroupLangauges()
    {
        return $this->hasMany('Modules\MenuManagement\Entities\ItemModifierGroupLanguage','modifier_group_id');
    }



   
}

Modules/MenuManagement/Resources/views/ItemModifierGroup/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="main__container container__custom">
        <div class="reservation__atto">
            <div class="reservation__title">
                <h1>{{ __('Item Modifier Group - Add') }}</h1>

            </div>

        </div>

        <div>

            <div class="card form__container">
                                    @include('menumanagement::common.message')

                <div class="card-body">
                    <div class="form__user__edit">
                        <form method="POST" action="{{ route('label.store') }}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row form_field__container">
                                <label for="restaurant_id"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Restaurant') }}</label>
                                <div class="col-md-4">
                                    <select name="restaurant_id" id="restaurant_id"
                                            class="form-control{{ $errors->has('restaurant_id') ? ' is-invalid' : '' }}"
                                            required>
                                        <option value="">Select Restaurant</option>
                                        @foreach($restaurantData as $rest)
                                            <optgroup label="{{ $rest['restaurant_name'] }}">
                                                @foreach($rest['branches'] as $branch)
                                                    <option value="{{ $branch['id'] }}" {{ (old('restaurant_id')==$branch['id']) ? 'selected' :'' }}>{{ $branch['restaurant_name'] }}</option>
                                                @endforeach
                                            </optgroup>
                                        @endforeach
                                    </select>
                                  
                                    @if ($errors->has('restaurant_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('restaurant_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row form_field__container">
                                <label for="priority"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                                <div class="col-md-4">
                                    <div class="input__field">
                                        <input id="group_name" type="text"
                                               class="{{ $errors->has('group_name') ? ' is-invalid' : '' }}"
                                               name="group_name" value="{{ old('group_name') }}" required>
                                    </div>
                                    @if ($errors->has('group_name'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('group_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row form_field__container">
                                <label for="priority"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Prompt') }}</label>
                                <div class="col-md-4">
                                    <div class="input__field">
                                        <input id="prompt" type="text"
                                               class="{{ $errors->has('prompt') ? ' is-invalid' : '' }}"
                                               name="prompt" value="{{ old('prompt') }}" required>
                                    </div>
                                    @if ($errors->has('prompt'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('prompt') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        <div class="form-group row form_field__container">
                            <label for="priority" class="col-md-4 col-form-label text-md-right">{{ __('Required') }}</label>
                            <div class="col-md-4" style="padding-top: 10px;">
                                <input type="radio" id="status1" name="is_required" value="1" {{ (old('is_required')=='1') ? 'checked' :'' }}   > Yes
                                &nbsp;&nbsp;&nbsp;&nbsp;
                                <input type="radio" id="status0" name="is_required" value="0" {{ (old('is_required')=='0') ? 'checked' :'' }}> No
                                @if ($errors->has('is_required'))
                                <span class="invalid-feedback" style="display:block;">
                                <strong>{{ $errors->first('is_required') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                             <div class="form-group row form_field__container">
                                <label for="quantity_type"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Quantity Type') }}</label>
                                <div class="col-md-4">
                                    <select name="quantity_type" id="quantity_type"
                                            class="form-control{{ $errors->has('quantity_type') ? ' is-invalid' : '' }}"
                                            required>
                                        <option value="">Select Quantity Type</option>
                                        <option value="Value">Value</option>
                                        <option value="Range">Range</option>
                                      
                                    </select>
                                  
                                    @if ($errors->has('restaurant_id'))
                                        <span class="invalid-feedback">
                                        <strong>{{ $errors->first('restaurant_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <br/><br/>
                            <div class=" mb-0 ">
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn__primary">{{ __('Save') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script type="text/javascript">
        var check_restaurant = '<?php echo $selected_rest_id;?>';
        if (check_restaurant != 0) {
            // trigger restautaurnat checks
            $("#restaurant_id").val(check_restaurant);
            //$("#restaurant_id").attr('change');
        }
    </script>

@endsection

Modules/MenuManagement/Resources/views/ItemModifierGroup/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="main__container container__custom">
        <div class="reservation__atto">
            <div class="reservation__title">
                <h1>{{ __('Item Modifier Group - Edit') }}</h1>

            </div>

        </div>

        <div>

            <div class="card form__container">
                 @include('menumanagement::common.message')

                <div class="card-body">
                    <div class="form__user__edit">
                        {{ Form::model($data, array('route' => array('label.update', $data->id), 'method' => 'PUT')) }}

                        @csrf

                        <div class="form-group row form_field__container">
                            <label for="restaurant_id"
                                   class="col-md-4 col-form-label text-md-right">{{ __('Restaurant') }}</label>
                            <div class="col-md-4">
                                <select name="restaurant_id" id="restaurant_id"
                                        class="form-control{{ $errors->has('restaurant_id') ? ' is-invalid' : '' }}"
                                        required>
                                    @foreach($restaurantData as $rest)
                                        <optgroup label="{{ $rest['restaurant_name'] }}">
                                            @foreach($rest['branches'] as $branch)
                                                <option value="{{ $branch['id'] }}" {{ ((old('restaurant_id')==$branch['id']) || (isset($data->restaurant_id) && $data->restaurant_id==$branch['id'])) ? 'selected' :'' }}>{{ $branch['restaurant_name'] }}</option>
                                            @endforeach
                                        </optgroup>
                                    @endforeach
                                </select>
                                
                                @if ($errors->has('restaurant_id'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('restaurant_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row form_field__container">
                            <label for="priority" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                            <div class="col-md-4">
                                <div class="input__field">
                                    <input id="label_name" type="text"
                                           class="{{ $errors->has('label_name') ? ' is-invalid' : '' }}"
                                           name="label_name" value="{{ isset($data->label_name)?$data->label_name:old('label_name') }}"
                                           required>
                                </div>
                                @if ($errors->has('label_name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('label_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                       

                        <br/><br/>
                        <div class=" row mb-0">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn__primary">{{ __('Save') }}</button>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>

  
@endsection

Modules/MenuManagement/Resources/views/ItemModifierGroup/index.blade.php
@extends('layouts.app')

@section('content')
<div class="main__container container__custom">
  <div class="reservation__atto">
    <div class="reservation__title">
      <h1>Item Modifier Group<span style="margin:0px 5px;">({{ $data->currentPage() .'/' . $data->lastPage() }})</span>&emsp;</h1>
    </div>
    <span style="float: right;margin:auto 5px;"><a href="{{ URL::to('menu/modifier-group/create') }}" class="btn btn__primary">Add</a></span>
  </div>
  <div class="addition__functionality">
    {!! Form::open(['method'=>'get']) !!}
    <div class="row functionality__wrapper">
      <div class="row form-group col-md-2">
        <select name="restaurant_id" id="restaurant_id" class="" >
          <option value="">Select Restaurant</option>
          @foreach($restaurantData as $rest)
          <option value="{{ $rest->id }}" {{ (isset($restaurant_id) && $restaurant_id==$rest->id) ? 'selected' :'' }}>{{ $rest->restaurant_name }}</option>
          @endforeach
        </select>
      </div>
      <div class="row form-group col-md-5">
        <button class="btn btn__primary" style="margin-left: 5px;" type="submit" >Search</button>
      </div>
    </div>
    {!! Form::close() !!}
  </div>

  <div>

    <div class="active__order__container">

      @include('menumanagement::common.message')

      <div class="guestbook__container box-shadow">
        <div class="guestbook__table-header hidden-xs hidden-sm hidden-tablet row plr0">

          <div class="col-md-10">
            <div class="col-md-3" style="font-weight: bold;">Name</div>
            <div class="col-md-3" style="font-weight: bold;">Prompt</div>
            <div class="col-md-3" style="font-weight: bold;">Is Required</div>
            <div class="col-md-3" style="font-weight: bold;">Restaurant</div>
          </div>

          <div class="col-md-2">
            <div class="col-md-12" style="font-weight: bold;">Action</div>
          </div>

        </div>
        @if(isset($data) && count($data)>0)
        @foreach($data as $record)
        <div class="guestbook__customer-details-content rest__row">
          <div class="col-md-10 order__row">

            <div class="col-md-5">{{ $record->group_name}}</div>
            <div class="col-md-5">{{ $record->prompt}}</div>
            <div class="col-md-5">{{ ($record->is_required==1?'Yes':'No')}}</div>
            <div class="col-md-5">{{ $record->restaurant->restaurant_name }}</div>
          </div>
          <div class="row col-md-2">
            <div class="col-md-12">
              <a style="width:100%;margin:10px 0;" href="{{ URL::to('menu/modifier-group/' . $record->id . '/edit') }}" class="btn btn__primary"><span class="fa fa-pencil"></span> Edit</a>
            </div>
            <div class="col-md-12">
              {!! Form::open(['method' => 'DELETE', 'route' => ['modifier-group.destroy', $record->id]]) !!}
              @csrf
              <button style="width:100%;margin:10px 0;" class="btn btn__cancel" type="submit"><span class="glyphicon glyphicon-trash"></span> Delete</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
        @endforeach
        @else
        <div class="row" style="text-align: center;justify-content: center;border:1px solid rgba(0, 0, 0, 0.03);">
          No Record Found
        </div>
        @endif
      </div>
      @if(isset($data) && count($data)>0)
      <div class="text-center" style="margin: 0px auto;text-align: center;">
        {{ $data->appends($_GET)->links()}}
      </div>
      @endif
    </div>

  </div>
</div>
@endsection